import { db } from './server/db';
import { stocks } from './shared/schema';
import { log } from './server/vite';
import { eq } from 'drizzle-orm';

// ข้อมูลคริปโตเพิ่มเติม
const additionalCryptos = [
  {
    symbol: 'TOMO',
    name: 'TomoChain',
    exchange: 'CRYPTO',
    currentPrice: 1.32,
    previousClose: 1.28,
    change: 0.04,
    changePercent: 3.12,
    logoUrl: 'https://cryptologos.cc/logos/tomochain-tomo-logo.png',
    sector: 'Cryptocurrency',
    description: 'https://tomochain.com/',
    asset_type: 'crypto',
    sentimentScore: Math.random() * 2 - 1,
    sentimentVolume: Math.floor(Math.random() * 10000),
    sentimentTrend: ['bullish', 'bearish', 'neutral', 'mixed'][Math.floor(Math.random() * 4)],
  },
  {
    symbol: 'HOT',
    name: 'Holo',
    exchange: 'CRYPTO',
    currentPrice: 0.00231,
    previousClose: 0.00224,
    change: 0.00007,
    changePercent: 3.13,
    logoUrl: 'https://cryptologos.cc/logos/holo-hot-logo.png',
    sector: 'Cryptocurrency',
    description: 'https://holochain.org/',
    asset_type: 'crypto',
    sentimentScore: Math.random() * 2 - 1,
    sentimentVolume: Math.floor(Math.random() * 10000),
    sentimentTrend: ['bullish', 'bearish', 'neutral', 'mixed'][Math.floor(Math.random() * 4)],
  },
  {
    symbol: 'BAT',
    name: 'Basic Attention Token',
    exchange: 'CRYPTO',
    currentPrice: 0.2543,
    previousClose: 0.2476,
    change: 0.0067,
    changePercent: 2.71,
    logoUrl: 'https://cryptologos.cc/logos/basic-attention-token-bat-logo.png',
    sector: 'Cryptocurrency',
    description: 'https://basicattentiontoken.org/',
    asset_type: 'crypto',
    sentimentScore: Math.random() * 2 - 1,
    sentimentVolume: Math.floor(Math.random() * 10000),
    sentimentTrend: ['bullish', 'bearish', 'neutral', 'mixed'][Math.floor(Math.random() * 4)],
  },
  {
    symbol: 'ZIL',
    name: 'Zilliqa',
    exchange: 'CRYPTO',
    currentPrice: 0.0234,
    previousClose: 0.0228,
    change: 0.0006,
    changePercent: 2.63,
    logoUrl: 'https://cryptologos.cc/logos/zilliqa-zil-logo.png',
    sector: 'Cryptocurrency',
    description: 'https://www.zilliqa.com/',
    asset_type: 'crypto',
    sentimentScore: Math.random() * 2 - 1,
    sentimentVolume: Math.floor(Math.random() * 10000),
    sentimentTrend: ['bullish', 'bearish', 'neutral', 'mixed'][Math.floor(Math.random() * 4)],
  },
  {
    symbol: 'ONE',
    name: 'Harmony',
    exchange: 'CRYPTO',
    currentPrice: 0.0145,
    previousClose: 0.0141,
    change: 0.0004,
    changePercent: 2.84,
    logoUrl: 'https://cryptologos.cc/logos/harmony-one-logo.png',
    sector: 'Cryptocurrency',
    description: 'https://www.harmony.one/',
    asset_type: 'crypto',
    sentimentScore: Math.random() * 2 - 1,
    sentimentVolume: Math.floor(Math.random() * 10000),
    sentimentTrend: ['bullish', 'bearish', 'neutral', 'mixed'][Math.floor(Math.random() * 4)],
  },
  {
    symbol: 'SRM',
    name: 'Serum',
    exchange: 'CRYPTO',
    currentPrice: 0.0978,
    previousClose: 0.0945,
    change: 0.0033,
    changePercent: 3.49,
    logoUrl: 'https://cryptologos.cc/logos/serum-srm-logo.png',
    sector: 'Cryptocurrency',
    description: 'https://www.projectserum.com/',
    asset_type: 'crypto',
    sentimentScore: Math.random() * 2 - 1,
    sentimentVolume: Math.floor(Math.random() * 10000),
    sentimentTrend: ['bullish', 'bearish', 'neutral', 'mixed'][Math.floor(Math.random() * 4)],
  },
  {
    symbol: 'ROSE',
    name: 'Oasis Network',
    exchange: 'CRYPTO',
    currentPrice: 0.0934,
    previousClose: 0.0897,
    change: 0.0037,
    changePercent: 4.12,
    logoUrl: 'https://cryptologos.cc/logos/oasis-network-rose-logo.png',
    sector: 'Cryptocurrency',
    description: 'https://oasisprotocol.org/',
    asset_type: 'crypto',
    sentimentScore: Math.random() * 2 - 1,
    sentimentVolume: Math.floor(Math.random() * 10000),
    sentimentTrend: ['bullish', 'bearish', 'neutral', 'mixed'][Math.floor(Math.random() * 4)],
  },
  {
    symbol: 'HNT',
    name: 'Helium',
    exchange: 'CRYPTO',
    currentPrice: 2.81,
    previousClose: 2.73,
    change: 0.08,
    changePercent: 2.93,
    logoUrl: 'https://cryptologos.cc/logos/helium-hnt-logo.png',
    sector: 'Cryptocurrency',
    description: 'https://www.helium.com/',
    asset_type: 'crypto',
    sentimentScore: Math.random() * 2 - 1,
    sentimentVolume: Math.floor(Math.random() * 10000),
    sentimentTrend: ['bullish', 'bearish', 'neutral', 'mixed'][Math.floor(Math.random() * 4)],
  },
  {
    symbol: 'KSM',
    name: 'Kusama',
    exchange: 'CRYPTO',
    currentPrice: 26.43,
    previousClose: 25.78,
    change: 0.65,
    changePercent: 2.52,
    logoUrl: 'https://cryptologos.cc/logos/kusama-ksm-logo.png',
    sector: 'Cryptocurrency',
    description: 'https://kusama.network/',
    asset_type: 'crypto',
    sentimentScore: Math.random() * 2 - 1,
    sentimentVolume: Math.floor(Math.random() * 10000),
    sentimentTrend: ['bullish', 'bearish', 'neutral', 'mixed'][Math.floor(Math.random() * 4)],
  },
  {
    symbol: 'CELO',
    name: 'Celo',
    exchange: 'CRYPTO',
    currentPrice: 0.687,
    previousClose: 0.662,
    change: 0.025,
    changePercent: 3.78,
    logoUrl: 'https://cryptologos.cc/logos/celo-celo-logo.png',
    sector: 'Cryptocurrency',
    description: 'https://celo.org/',
    asset_type: 'crypto',
    sentimentScore: Math.random() * 2 - 1,
    sentimentVolume: Math.floor(Math.random() * 10000),
    sentimentTrend: ['bullish', 'bearish', 'neutral', 'mixed'][Math.floor(Math.random() * 4)],
  },
  // Begin Additional Cryptos
  {
    symbol: 'BNT',
    name: 'Bancor',
    exchange: 'CRYPTO',
    currentPrice: 0.432,
    previousClose: 0.421,
    change: 0.011,
    changePercent: 2.61,
    logoUrl: 'https://cryptologos.cc/logos/bancor-bnt-logo.png',
    sector: 'Cryptocurrency',
    description: 'https://bancor.network/',
    asset_type: 'crypto',
    sentimentScore: Math.random() * 2 - 1,
    sentimentVolume: Math.floor(Math.random() * 10000),
    sentimentTrend: ['bullish', 'bearish', 'neutral', 'mixed'][Math.floor(Math.random() * 4)],
  },
  {
    symbol: 'QTUM',
    name: 'Qtum',
    exchange: 'CRYPTO',
    currentPrice: 2.83,
    previousClose: 2.75,
    change: 0.08,
    changePercent: 2.91,
    logoUrl: 'https://cryptologos.cc/logos/qtum-qtum-logo.png',
    sector: 'Cryptocurrency',
    description: 'https://qtum.org/',
    asset_type: 'crypto',
    sentimentScore: Math.random() * 2 - 1,
    sentimentVolume: Math.floor(Math.random() * 10000),
    sentimentTrend: ['bullish', 'bearish', 'neutral', 'mixed'][Math.floor(Math.random() * 4)],
  },
  {
    symbol: 'CELR',
    name: 'Celer Network',
    exchange: 'CRYPTO',
    currentPrice: 0.0178,
    previousClose: 0.0172,
    change: 0.0006,
    changePercent: 3.49,
    logoUrl: 'https://cryptologos.cc/logos/celer-network-celr-logo.png',
    sector: 'Cryptocurrency',
    description: 'https://www.celer.network/',
    asset_type: 'crypto',
    sentimentScore: Math.random() * 2 - 1,
    sentimentVolume: Math.floor(Math.random() * 10000),
    sentimentTrend: ['bullish', 'bearish', 'neutral', 'mixed'][Math.floor(Math.random() * 4)],
  },
  {
    symbol: 'POLY',
    name: 'Polymath',
    exchange: 'CRYPTO',
    currentPrice: 0.154,
    previousClose: 0.149,
    change: 0.005,
    changePercent: 3.36,
    logoUrl: 'https://cryptologos.cc/logos/polymath-network-poly-logo.png',
    sector: 'Cryptocurrency',
    description: 'https://www.polymath.network/',
    asset_type: 'crypto',
    sentimentScore: Math.random() * 2 - 1,
    sentimentVolume: Math.floor(Math.random() * 10000),
    sentimentTrend: ['bullish', 'bearish', 'neutral', 'mixed'][Math.floor(Math.random() * 4)],
  },
  {
    symbol: 'STORJ',
    name: 'Storj',
    exchange: 'CRYPTO',
    currentPrice: 0.387,
    previousClose: 0.376,
    change: 0.011,
    changePercent: 2.93,
    logoUrl: 'https://cryptologos.cc/logos/storj-storj-logo.png',
    sector: 'Cryptocurrency',
    description: 'https://storj.io/',
    asset_type: 'crypto',
    sentimentScore: Math.random() * 2 - 1,
    sentimentVolume: Math.floor(Math.random() * 10000),
    sentimentTrend: ['bullish', 'bearish', 'neutral', 'mixed'][Math.floor(Math.random() * 4)],
  },
  {
    symbol: 'API3',
    name: 'API3',
    exchange: 'CRYPTO',
    currentPrice: 1.42,
    previousClose: 1.37,
    change: 0.05,
    changePercent: 3.65,
    logoUrl: 'https://cryptologos.cc/logos/api3-api3-logo.png',
    sector: 'Cryptocurrency',
    description: 'https://api3.org/',
    asset_type: 'crypto',
    sentimentScore: Math.random() * 2 - 1,
    sentimentVolume: Math.floor(Math.random() * 10000),
    sentimentTrend: ['bullish', 'bearish', 'neutral', 'mixed'][Math.floor(Math.random() * 4)],
  },
  {
    symbol: 'ANKR',
    name: 'Ankr',
    exchange: 'CRYPTO',
    currentPrice: 0.0243,
    previousClose: 0.0236,
    change: 0.0007,
    changePercent: 2.97,
    logoUrl: 'https://cryptologos.cc/logos/ankr-ankr-logo.png',
    sector: 'Cryptocurrency',
    description: 'https://www.ankr.com/',
    asset_type: 'crypto',
    sentimentScore: Math.random() * 2 - 1,
    sentimentVolume: Math.floor(Math.random() * 10000),
    sentimentTrend: ['bullish', 'bearish', 'neutral', 'mixed'][Math.floor(Math.random() * 4)],
  },
  {
    symbol: 'REN',
    name: 'Ren',
    exchange: 'CRYPTO',
    currentPrice: 0.0654,
    previousClose: 0.0636,
    change: 0.0018,
    changePercent: 2.83,
    logoUrl: 'https://cryptologos.cc/logos/ren-ren-logo.png',
    sector: 'Cryptocurrency',
    description: 'https://renproject.io/',
    asset_type: 'crypto',
    sentimentScore: Math.random() * 2 - 1,
    sentimentVolume: Math.floor(Math.random() * 10000),
    sentimentTrend: ['bullish', 'bearish', 'neutral', 'mixed'][Math.floor(Math.random() * 4)],
  },
  {
    symbol: 'ICX',
    name: 'ICON',
    exchange: 'CRYPTO',
    currentPrice: 0.192,
    previousClose: 0.187,
    change: 0.005,
    changePercent: 2.67,
    logoUrl: 'https://cryptologos.cc/logos/icon-icx-logo.png',
    sector: 'Cryptocurrency',
    description: 'https://iconrepublic.org/',
    asset_type: 'crypto',
    sentimentScore: Math.random() * 2 - 1,
    sentimentVolume: Math.floor(Math.random() * 10000),
    sentimentTrend: ['bullish', 'bearish', 'neutral', 'mixed'][Math.floor(Math.random() * 4)],
  },
  {
    symbol: 'CHZ',
    name: 'Chiliz',
    exchange: 'CRYPTO',
    currentPrice: 0.0787,
    previousClose: 0.0762,
    change: 0.0025,
    changePercent: 3.28,
    logoUrl: 'https://cryptologos.cc/logos/chiliz-chz-logo.png',
    sector: 'Cryptocurrency',
    description: 'https://www.chiliz.com/',
    asset_type: 'crypto',
    sentimentScore: Math.random() * 2 - 1,
    sentimentVolume: Math.floor(Math.random() * 10000),
    sentimentTrend: ['bullish', 'bearish', 'neutral', 'mixed'][Math.floor(Math.random() * 4)],
  },
  {
    symbol: 'WOO',
    name: 'WOO Network',
    exchange: 'CRYPTO',
    currentPrice: 0.327,
    previousClose: 0.318,
    change: 0.009,
    changePercent: 2.83,
    logoUrl: 'https://cryptologos.cc/logos/woo-network-woo-logo.png',
    sector: 'Cryptocurrency',
    description: 'https://woo.org/',
    asset_type: 'crypto',
    sentimentScore: Math.random() * 2 - 1,
    sentimentVolume: Math.floor(Math.random() * 10000),
    sentimentTrend: ['bullish', 'bearish', 'neutral', 'mixed'][Math.floor(Math.random() * 4)],
  },
  {
    symbol: 'QNT',
    name: 'Quant',
    exchange: 'CRYPTO',
    currentPrice: 104.56,
    previousClose: 101.37,
    change: 3.19,
    changePercent: 3.15,
    logoUrl: 'https://cryptologos.cc/logos/quant-qnt-logo.png',
    sector: 'Cryptocurrency',
    description: 'https://quant.network/',
    asset_type: 'crypto',
    sentimentScore: Math.random() * 2 - 1,
    sentimentVolume: Math.floor(Math.random() * 10000),
    sentimentTrend: ['bullish', 'bearish', 'neutral', 'mixed'][Math.floor(Math.random() * 4)],
  },
  {
    symbol: 'SNX',
    name: 'Synthetix',
    exchange: 'CRYPTO',
    currentPrice: 2.87,
    previousClose: 2.78,
    change: 0.09,
    changePercent: 3.24,
    logoUrl: 'https://cryptologos.cc/logos/synthetix-network-token-snx-logo.png',
    sector: 'Cryptocurrency',
    description: 'https://synthetix.io/',
    asset_type: 'crypto',
    sentimentScore: Math.random() * 2 - 1,
    sentimentVolume: Math.floor(Math.random() * 10000),
    sentimentTrend: ['bullish', 'bearish', 'neutral', 'mixed'][Math.floor(Math.random() * 4)],
  },
  {
    symbol: 'IOTA',
    name: 'IOTA',
    exchange: 'CRYPTO',
    currentPrice: 0.196,
    previousClose: 0.191,
    change: 0.005,
    changePercent: 2.62,
    logoUrl: 'https://cryptologos.cc/logos/iota-miota-logo.png',
    sector: 'Cryptocurrency',
    description: 'https://www.iota.org/',
    asset_type: 'crypto',
    sentimentScore: Math.random() * 2 - 1,
    sentimentVolume: Math.floor(Math.random() * 10000),
    sentimentTrend: ['bullish', 'bearish', 'neutral', 'mixed'][Math.floor(Math.random() * 4)],
  },
  {
    symbol: 'XNO',
    name: 'Nano',
    exchange: 'CRYPTO',
    currentPrice: 0.765,
    previousClose: 0.743,
    change: 0.022,
    changePercent: 2.96,
    logoUrl: 'https://cryptologos.cc/logos/nano-nano-logo.png',
    sector: 'Cryptocurrency',
    description: 'https://nano.org/',
    asset_type: 'crypto',
    sentimentScore: Math.random() * 2 - 1,
    sentimentVolume: Math.floor(Math.random() * 10000),
    sentimentTrend: ['bullish', 'bearish', 'neutral', 'mixed'][Math.floor(Math.random() * 4)],
  },
  {
    symbol: 'FLUX',
    name: 'Flux',
    exchange: 'CRYPTO',
    currentPrice: 0.534,
    previousClose: 0.515,
    change: 0.019,
    changePercent: 3.69,
    logoUrl: 'https://cryptologos.cc/logos/flux-flux-logo.png',
    sector: 'Cryptocurrency',
    description: 'https://runonflux.io/',
    asset_type: 'crypto',
    sentimentScore: Math.random() * 2 - 1,
    sentimentVolume: Math.floor(Math.random() * 10000),
    sentimentTrend: ['bullish', 'bearish', 'neutral', 'mixed'][Math.floor(Math.random() * 4)],
  }
];

// ฟังก์ชั่นเพิ่มคริปโตในฐานข้อมูล
async function addMoreCryptosToDatabase() {
  try {
    console.log('เริ่มต้นเพิ่มข้อมูลคริปโตเพิ่มเติม...');
    
    // อ่านข้อมูลคริปโตที่มีอยู่แล้ว
    const existingCryptos = await db.select({
      symbol: stocks.symbol,
    }).from(stocks).where(eq(stocks.asset_type, 'crypto'));
    
    // สร้างชุดข้อมูลของสัญลักษณ์คริปโตที่มีอยู่แล้ว
    const existingSymbols = new Set(existingCryptos.map(c => c.symbol));
    
    // กรองเฉพาะคริปโตที่ยังไม่มีในระบบ
    const newCryptos = additionalCryptos.filter(crypto => !existingSymbols.has(crypto.symbol));
    
    if (newCryptos.length === 0) {
      console.log('ไม่มีคริปโตใหม่ที่ต้องเพิ่ม');
      return;
    }
    
    // เพิ่มคริปโตใหม่ลงในฐานข้อมูล
    await db.insert(stocks).values(newCryptos);
    
    console.log(`เพิ่มคริปโตใหม่ ${newCryptos.length} รายการสำเร็จ`);
    console.log('รายการคริปโตที่เพิ่ม:');
    newCryptos.forEach(crypto => {
      console.log(`- ${crypto.symbol} (${crypto.name})`);
    });
  } catch (error) {
    console.error('เกิดข้อผิดพลาดในการเพิ่มคริปโต:', error);
    throw error;
  }
}

// Export function เพื่อให้สามารถเรียกใช้งานจากไฟล์อื่นได้
export { addMoreCryptosToDatabase };

// รันฟังก์ชั่นเพิ่มคริปโตเมื่อรันไฟล์นี้โดยตรง
if (require.main === module) {
  addMoreCryptosToDatabase()
    .then(() => {
      console.log('เสร็จสิ้นการเพิ่มคริปโตเพิ่มเติม');
      process.exit(0);
    })
    .catch(error => {
      console.error('เกิดข้อผิดพลาด:', error);
      process.exit(1);
    });
}