// This file contains static mock data for cryptocurrencies
// In production, these would be replaced with real data from cryptocurrency APIs

export const mockCryptos = [
  {
    symbol: 'BTC',
    name: 'Bitcoin',
    exchange: 'CRYPTO',
    currentPrice: 65234.78,
    previousClose: 64578.92,
    change: 655.86,
    changePercent: 1.02,
    logoUrl: 'https://cryptologos.cc/logos/bitcoin-btc-logo.png',
    sector: 'Cryptocurrency',
    description: 'https://bitcoin.org/',
    assetType: 'crypto'
  },
  {
    symbol: 'ETH',
    name: 'Ethereum',
    exchange: 'CRYPTO',
    currentPrice: 3456.23,
    previousClose: 3398.65,
    change: 57.58,
    changePercent: 1.69,
    logoUrl: 'https://cryptologos.cc/logos/ethereum-eth-logo.png',
    sector: 'Cryptocurrency',
    description: 'https://ethereum.org/',
    assetType: 'crypto'
  },
  {
    symbol: 'BNB',
    name: 'Binance Coin',
    exchange: 'CRYPTO',
    currentPrice: 567.89,
    previousClose: 573.21,
    change: -5.32,
    changePercent: -0.93,
    logoUrl: 'https://cryptologos.cc/logos/bnb-bnb-logo.png',
    sector: 'Cryptocurrency',
    description: 'https://www.binance.com/',
    assetType: 'crypto'
  },
  {
    symbol: 'SOL',
    name: 'Solana',
    exchange: 'CRYPTO',
    currentPrice: 142.65,
    previousClose: 139.87,
    change: 2.78,
    changePercent: 1.99,
    logoUrl: 'https://cryptologos.cc/logos/solana-sol-logo.png',
    sector: 'Cryptocurrency',
    description: 'https://solana.com/',
    assetType: 'crypto'
  },
  {
    symbol: 'XRP',
    name: 'XRP',
    exchange: 'CRYPTO',
    currentPrice: 0.5423,
    previousClose: 0.5312,
    change: 0.0111,
    changePercent: 2.09,
    logoUrl: 'https://cryptologos.cc/logos/xrp-xrp-logo.png',
    sector: 'Cryptocurrency',
    description: 'https://ripple.com/xrp/',
    assetType: 'crypto'
  },
  {
    symbol: 'ADA',
    name: 'Cardano',
    exchange: 'CRYPTO',
    currentPrice: 0.4532,
    previousClose: 0.4498,
    change: 0.0034,
    changePercent: 0.76,
    logoUrl: 'https://cryptologos.cc/logos/cardano-ada-logo.png',
    sector: 'Cryptocurrency',
    description: 'https://cardano.org/',
    assetType: 'crypto'
  },
  {
    symbol: 'AVAX',
    name: 'Avalanche',
    exchange: 'CRYPTO',
    currentPrice: 34.56,
    previousClose: 33.89,
    change: 0.67,
    changePercent: 1.98,
    logoUrl: 'https://cryptologos.cc/logos/avalanche-avax-logo.png',
    sector: 'Cryptocurrency',
    description: 'https://www.avax.network/',
    assetType: 'crypto'
  },
  {
    symbol: 'DOT',
    name: 'Polkadot',
    exchange: 'CRYPTO',
    currentPrice: 6.78,
    previousClose: 6.92,
    change: -0.14,
    changePercent: -2.02,
    logoUrl: 'https://cryptologos.cc/logos/polkadot-new-dot-logo.png',
    sector: 'Cryptocurrency',
    description: 'https://polkadot.network/',
    assetType: 'crypto'
  },
  {
    symbol: 'DOGE',
    name: 'Dogecoin',
    exchange: 'CRYPTO',
    currentPrice: 0.1234,
    previousClose: 0.1198,
    change: 0.0036,
    changePercent: 3.00,
    logoUrl: 'https://cryptologos.cc/logos/dogecoin-doge-logo.png',
    sector: 'Cryptocurrency',
    description: 'https://dogecoin.com/',
    assetType: 'crypto'
  },
  {
    symbol: 'SHIB',
    name: 'Shiba Inu',
    exchange: 'CRYPTO',
    currentPrice: 0.00002345,
    previousClose: 0.00002289,
    change: 0.00000056,
    changePercent: 2.45,
    logoUrl: 'https://cryptologos.cc/logos/shiba-inu-shib-logo.png',
    sector: 'Cryptocurrency',
    description: 'https://shibatoken.com/',
    assetType: 'crypto'
  },
  {
    symbol: 'MATIC',
    name: 'Polygon',
    exchange: 'CRYPTO',
    currentPrice: 0.7654,
    previousClose: 0.7821,
    change: -0.0167,
    changePercent: -2.14,
    logoUrl: 'https://cryptologos.cc/logos/polygon-matic-logo.png',
    sector: 'Cryptocurrency',
    description: 'https://polygon.technology/',
    assetType: 'crypto'
  },
  {
    symbol: 'LINK',
    name: 'Chainlink',
    exchange: 'CRYPTO',
    currentPrice: 14.32,
    previousClose: 13.98,
    change: 0.34,
    changePercent: 2.43,
    logoUrl: 'https://cryptologos.cc/logos/chainlink-link-logo.png',
    sector: 'Cryptocurrency',
    description: 'https://chain.link/',
    assetType: 'crypto'
  },
  {
    symbol: 'UNI',
    name: 'Uniswap',
    exchange: 'CRYPTO',
    currentPrice: 10.45,
    previousClose: 10.23,
    change: 0.22,
    changePercent: 2.15,
    logoUrl: 'https://cryptologos.cc/logos/uniswap-uni-logo.png',
    sector: 'Cryptocurrency',
    description: 'https://uniswap.org/',
    assetType: 'crypto'
  },
  {
    symbol: 'LTC',
    name: 'Litecoin',
    exchange: 'CRYPTO',
    currentPrice: 78.54,
    previousClose: 77.89,
    change: 0.65,
    changePercent: 0.83,
    logoUrl: 'https://cryptologos.cc/logos/litecoin-ltc-logo.png',
    sector: 'Cryptocurrency',
    description: 'https://litecoin.org/',
    assetType: 'crypto'
  },
  {
    symbol: 'BCH',
    name: 'Bitcoin Cash',
    exchange: 'CRYPTO',
    currentPrice: 341.23,
    previousClose: 336.78,
    change: 4.45,
    changePercent: 1.32,
    logoUrl: 'https://cryptologos.cc/logos/bitcoin-cash-bch-logo.png',
    sector: 'Cryptocurrency',
    description: 'https://bitcoincash.org/',
    assetType: 'crypto'
  },
  {
    symbol: 'XLM',
    name: 'Stellar',
    exchange: 'CRYPTO',
    currentPrice: 0.1167,
    previousClose: 0.1145,
    change: 0.0022,
    changePercent: 1.92,
    logoUrl: 'https://cryptologos.cc/logos/stellar-xlm-logo.png',
    sector: 'Cryptocurrency',
    description: 'https://www.stellar.org/',
    assetType: 'crypto'
  },
  {
    symbol: 'ATOM',
    name: 'Cosmos',
    exchange: 'CRYPTO',
    currentPrice: 9.34,
    previousClose: 9.12,
    change: 0.22,
    changePercent: 2.41,
    logoUrl: 'https://cryptologos.cc/logos/cosmos-atom-logo.png',
    sector: 'Cryptocurrency',
    description: 'https://cosmos.network/',
    assetType: 'crypto'
  },
  {
    symbol: 'ETC',
    name: 'Ethereum Classic',
    exchange: 'CRYPTO',
    currentPrice: 24.56,
    previousClose: 24.12,
    change: 0.44,
    changePercent: 1.82,
    logoUrl: 'https://cryptologos.cc/logos/ethereum-classic-etc-logo.png',
    sector: 'Cryptocurrency',
    description: 'https://ethereumclassic.org/',
    assetType: 'crypto'
  },
  {
    symbol: 'FIL',
    name: 'Filecoin',
    exchange: 'CRYPTO',
    currentPrice: 4.78,
    previousClose: 4.65,
    change: 0.13,
    changePercent: 2.80,
    logoUrl: 'https://cryptologos.cc/logos/filecoin-fil-logo.png',
    sector: 'Cryptocurrency',
    description: 'https://filecoin.io/',
    assetType: 'crypto'
  },
  {
    symbol: 'VET',
    name: 'VeChain',
    exchange: 'CRYPTO',
    currentPrice: 0.0245,
    previousClose: 0.0238,
    change: 0.0007,
    changePercent: 2.94,
    logoUrl: 'https://cryptologos.cc/logos/vechain-vet-logo.png',
    sector: 'Cryptocurrency',
    description: 'https://www.vechain.org/',
    assetType: 'crypto'
  },
  {
    symbol: 'ALGO',
    name: 'Algorand',
    exchange: 'CRYPTO',
    currentPrice: 0.1623,
    previousClose: 0.1598,
    change: 0.0025,
    changePercent: 1.56,
    logoUrl: 'https://cryptologos.cc/logos/algorand-algo-logo.png',
    sector: 'Cryptocurrency',
    description: 'https://www.algorand.com/',
    assetType: 'crypto'
  },
  {
    symbol: 'ICP',
    name: 'Internet Computer',
    exchange: 'CRYPTO',
    currentPrice: 11.23,
    previousClose: 10.89,
    change: 0.34,
    changePercent: 3.12,
    logoUrl: 'https://cryptologos.cc/logos/internet-computer-icp-logo.png',
    sector: 'Cryptocurrency',
    description: 'https://internetcomputer.org/',
    assetType: 'crypto'
  },
  {
    symbol: 'NEAR',
    name: 'NEAR Protocol',
    exchange: 'CRYPTO',
    currentPrice: 5.67,
    previousClose: 5.45,
    change: 0.22,
    changePercent: 4.04,
    logoUrl: 'https://cryptologos.cc/logos/near-protocol-near-logo.png',
    sector: 'Cryptocurrency',
    description: 'https://near.org/',
    assetType: 'crypto'
  },
  {
    symbol: 'AAVE',
    name: 'Aave',
    exchange: 'CRYPTO',
    currentPrice: 89.34,
    previousClose: 87.65,
    change: 1.69,
    changePercent: 1.93,
    logoUrl: 'https://cryptologos.cc/logos/aave-aave-logo.png',
    sector: 'Cryptocurrency',
    description: 'https://aave.com/',
    assetType: 'crypto'
  },
  {
    symbol: 'AXS',
    name: 'Axie Infinity',
    exchange: 'CRYPTO',
    currentPrice: 7.23,
    previousClose: 6.98,
    change: 0.25,
    changePercent: 3.58,
    logoUrl: 'https://cryptologos.cc/logos/axie-infinity-axs-logo.png',
    sector: 'Cryptocurrency',
    description: 'https://axieinfinity.com/',
    assetType: 'crypto'
  },
  {
    symbol: 'SAND',
    name: 'The Sandbox',
    exchange: 'CRYPTO',
    currentPrice: 0.4567,
    previousClose: 0.4432,
    change: 0.0135,
    changePercent: 3.05,
    logoUrl: 'https://cryptologos.cc/logos/the-sandbox-sand-logo.png',
    sector: 'Cryptocurrency',
    description: 'https://www.sandbox.game/',
    assetType: 'crypto'
  },
  {
    symbol: 'MANA',
    name: 'Decentraland',
    exchange: 'CRYPTO',
    currentPrice: 0.4321,
    previousClose: 0.4234,
    change: 0.0087,
    changePercent: 2.06,
    logoUrl: 'https://cryptologos.cc/logos/decentraland-mana-logo.png',
    sector: 'Cryptocurrency',
    description: 'https://decentraland.org/',
    assetType: 'crypto'
  },
  {
    symbol: 'MKR',
    name: 'Maker',
    exchange: 'CRYPTO',
    currentPrice: 1765.43,
    previousClose: 1723.98,
    change: 41.45,
    changePercent: 2.40,
    logoUrl: 'https://cryptologos.cc/logos/maker-mkr-logo.png',
    sector: 'Cryptocurrency',
    description: 'https://makerdao.com/',
    assetType: 'crypto'
  },
  {
    symbol: 'CRO',
    name: 'Cronos',
    exchange: 'CRYPTO',
    currentPrice: 0.0876,
    previousClose: 0.0854,
    change: 0.0022,
    changePercent: 2.58,
    logoUrl: 'https://cryptologos.cc/logos/cronos-cro-logo.png',
    sector: 'Cryptocurrency',
    description: 'https://cronos.org/',
    assetType: 'crypto'
  },
  {
    symbol: 'ZEC',
    name: 'Zcash',
    exchange: 'CRYPTO',
    currentPrice: 28.76,
    previousClose: 28.23,
    change: 0.53,
    changePercent: 1.88,
    logoUrl: 'https://cryptologos.cc/logos/zcash-zec-logo.png',
    sector: 'Cryptocurrency',
    description: 'https://z.cash/',
    assetType: 'crypto'
  },
  {
    symbol: 'ENJ',
    name: 'Enjin Coin',
    exchange: 'CRYPTO',
    currentPrice: 0.3456,
    previousClose: 0.3378,
    change: 0.0078,
    changePercent: 2.31,
    logoUrl: 'https://cryptologos.cc/logos/enjin-coin-enj-logo.png',
    sector: 'Cryptocurrency',
    description: 'https://enjin.io/',
    assetType: 'crypto'
  },
  {
    symbol: 'GRT',
    name: 'The Graph',
    exchange: 'CRYPTO',
    currentPrice: 0.1765,
    previousClose: 0.1723,
    change: 0.0042,
    changePercent: 2.44,
    logoUrl: 'https://cryptologos.cc/logos/the-graph-grt-logo.png',
    sector: 'Cryptocurrency',
    description: 'https://thegraph.com/',
    assetType: 'crypto'
  },
  {
    symbol: 'APE',
    name: 'ApeCoin',
    exchange: 'CRYPTO',
    currentPrice: 1.64,
    previousClose: 1.58,
    change: 0.06,
    changePercent: 3.80,
    logoUrl: 'https://cryptologos.cc/logos/apecoin-ape-logo.png',
    sector: 'Cryptocurrency',
    description: 'https://apecoin.com/',
    assetType: 'crypto'
  },
  {
    symbol: 'LDO',
    name: 'Lido DAO',
    exchange: 'CRYPTO',
    currentPrice: 2.46,
    previousClose: 2.38,
    change: 0.08,
    changePercent: 3.36,
    logoUrl: 'https://cryptologos.cc/logos/lido-dao-ldo-logo.png',
    sector: 'Cryptocurrency',
    description: 'https://lido.fi/',
    assetType: 'crypto'
  },
  {
    symbol: 'OP',
    name: 'Optimism',
    exchange: 'CRYPTO',
    currentPrice: 3.12,
    previousClose: 3.04,
    change: 0.08,
    changePercent: 2.63,
    logoUrl: 'https://cryptologos.cc/logos/optimism-op-logo.png',
    sector: 'Cryptocurrency',
    description: 'https://www.optimism.io/',
    assetType: 'crypto'
  },
  {
    symbol: 'ARB',
    name: 'Arbitrum',
    exchange: 'CRYPTO',
    currentPrice: 1.23,
    previousClose: 1.19,
    change: 0.04,
    changePercent: 3.36,
    logoUrl: 'https://cryptologos.cc/logos/arbitrum-arb-logo.png',
    sector: 'Cryptocurrency',
    description: 'https://arbitrum.io/',
    assetType: 'crypto'
  },
  {
    symbol: 'DYDX',
    name: 'dYdX',
    exchange: 'CRYPTO',
    currentPrice: 2.98,
    previousClose: 2.91,
    change: 0.07,
    changePercent: 2.41,
    logoUrl: 'https://cryptologos.cc/logos/dydx-dydx-logo.png',
    sector: 'Cryptocurrency',
    description: 'https://dydx.exchange/',
    assetType: 'crypto'
  },
  {
    symbol: 'IMX',
    name: 'Immutable X',
    exchange: 'CRYPTO',
    currentPrice: 2.34,
    previousClose: 2.27,
    change: 0.07,
    changePercent: 3.08,
    logoUrl: 'https://cryptologos.cc/logos/immutable-x-imx-logo.png',
    sector: 'Cryptocurrency',
    description: 'https://www.immutable.com/',
    assetType: 'crypto'
  },
  {
    symbol: 'INJ',
    name: 'Injective',
    exchange: 'CRYPTO',
    currentPrice: 31.24,
    previousClose: 30.12,
    change: 1.12,
    changePercent: 3.72,
    logoUrl: 'https://cryptologos.cc/logos/injective-inj-logo.png',
    sector: 'Cryptocurrency',
    description: 'https://injective.com/',
    assetType: 'crypto'
  },
  {
    symbol: 'STX',
    name: 'Stacks',
    exchange: 'CRYPTO',
    currentPrice: 2.43,
    previousClose: 2.37,
    change: 0.06,
    changePercent: 2.53,
    logoUrl: 'https://cryptologos.cc/logos/stacks-stx-logo.png',
    sector: 'Cryptocurrency',
    description: 'https://www.stacks.co/',
    assetType: 'crypto'
  },
  {
    symbol: 'EGLD',
    name: 'MultiversX',
    exchange: 'CRYPTO',
    currentPrice: 45.32,
    previousClose: 44.23,
    change: 1.09,
    changePercent: 2.46,
    logoUrl: 'https://cryptologos.cc/logos/multiversx-egld-logo.png',
    sector: 'Cryptocurrency',
    description: 'https://multiversx.com/',
    assetType: 'crypto'
  },
  {
    symbol: 'FET',
    name: 'Fetch.ai',
    exchange: 'CRYPTO',
    currentPrice: 1.76,
    previousClose: 1.69,
    change: 0.07,
    changePercent: 4.14,
    logoUrl: 'https://cryptologos.cc/logos/fetch-ai-fet-logo.png',
    sector: 'Cryptocurrency',
    description: 'https://fetch.ai/',
    assetType: 'crypto'
  },
  {
    symbol: 'KAS',
    name: 'Kaspa',
    exchange: 'CRYPTO',
    currentPrice: 0.1145,
    previousClose: 0.1098,
    change: 0.0047,
    changePercent: 4.28,
    logoUrl: 'https://cryptologos.cc/logos/kaspa-kas-logo.png',
    sector: 'Cryptocurrency',
    description: 'https://kaspa.org/',
    assetType: 'crypto'
  },
  {
    symbol: 'SEI',
    name: 'Sei',
    exchange: 'CRYPTO',
    currentPrice: 0.6543,
    previousClose: 0.6321,
    change: 0.0222,
    changePercent: 3.51,
    logoUrl: 'https://cryptologos.cc/logos/sei-sei-logo.png',
    sector: 'Cryptocurrency',
    description: 'https://www.sei.io/',
    assetType: 'crypto'
  },
  {
    symbol: 'RLY',
    name: 'Rally',
    exchange: 'CRYPTO',
    currentPrice: 0.0145,
    previousClose: 0.0139,
    change: 0.0006,
    changePercent: 4.32,
    logoUrl: 'https://cryptologos.cc/logos/rally-rly-logo.png',
    sector: 'Cryptocurrency',
    description: 'https://rally.io/',
    assetType: 'crypto'
  },
  {
    symbol: 'XVS',
    name: 'Venus',
    exchange: 'CRYPTO',
    currentPrice: 6.78,
    previousClose: 6.54,
    change: 0.24,
    changePercent: 3.67,
    logoUrl: 'https://cryptologos.cc/logos/venus-xvs-logo.png',
    sector: 'Cryptocurrency',
    description: 'https://venus.io/',
    assetType: 'crypto'
  },
  {
    symbol: 'CAKE',
    name: 'PancakeSwap',
    exchange: 'CRYPTO',
    currentPrice: 2.43,
    previousClose: 2.35,
    change: 0.08,
    changePercent: 3.40,
    logoUrl: 'https://cryptologos.cc/logos/pancakeswap-cake-logo.png',
    sector: 'Cryptocurrency',
    description: 'https://pancakeswap.finance/',
    assetType: 'crypto'
  },
  {
    symbol: 'COMP',
    name: 'Compound',
    exchange: 'CRYPTO',
    currentPrice: 56.78,
    previousClose: 55.43,
    change: 1.35,
    changePercent: 2.44,
    logoUrl: 'https://cryptologos.cc/logos/compound-comp-logo.png',
    sector: 'Cryptocurrency',
    description: 'https://compound.finance/',
    assetType: 'crypto'
  },
  {
    symbol: 'YFI',
    name: 'yearn.finance',
    exchange: 'CRYPTO',
    currentPrice: 7654.32,
    previousClose: 7543.21,
    change: 111.11,
    changePercent: 1.47,
    logoUrl: 'https://cryptologos.cc/logos/yearn-finance-yfi-logo.png',
    sector: 'Cryptocurrency',
    description: 'https://yearn.finance/',
    assetType: 'crypto'
  },
  {
    symbol: 'SUI',
    name: 'Sui',
    exchange: 'CRYPTO',
    currentPrice: 1.34,
    previousClose: 1.29,
    change: 0.05,
    changePercent: 3.88,
    logoUrl: 'https://cryptologos.cc/logos/sui-sui-logo.png',
    sector: 'Cryptocurrency',
    description: 'https://sui.io/',
    assetType: 'crypto'
  },
  {
    symbol: 'GALA',
    name: 'Gala',
    exchange: 'CRYPTO',
    currentPrice: 0.024,
    previousClose: 0.023,
    change: 0.001,
    changePercent: 4.35,
    logoUrl: 'https://cryptologos.cc/logos/gala-gala-logo.png',
    sector: 'Cryptocurrency',
    description: 'https://gala.games/',
    assetType: 'crypto'
  },
  {
    symbol: 'GMT',
    name: 'STEPN',
    exchange: 'CRYPTO',
    currentPrice: 0.34,
    previousClose: 0.33,
    change: 0.01,
    changePercent: 3.03,
    logoUrl: 'https://cryptologos.cc/logos/stepn-gmt-logo.png',
    sector: 'Cryptocurrency',
    description: 'https://stepn.com/',
    assetType: 'crypto'
  },
  {
    symbol: 'ROSE',
    name: 'Oasis Network',
    exchange: 'CRYPTO',
    currentPrice: 0.092,
    previousClose: 0.089,
    change: 0.003,
    changePercent: 3.37,
    logoUrl: 'https://cryptologos.cc/logos/oasis-network-rose-logo.png',
    sector: 'Cryptocurrency',
    description: 'https://oasisprotocol.org/',
    assetType: 'crypto'
  },
  {
    symbol: 'FTM',
    name: 'Fantom',
    exchange: 'CRYPTO',
    currentPrice: 0.54,
    previousClose: 0.52,
    change: 0.02,
    changePercent: 3.85,
    logoUrl: 'https://cryptologos.cc/logos/fantom-ftm-logo.png',
    sector: 'Cryptocurrency',
    description: 'https://fantom.foundation/',
    assetType: 'crypto'
  },
  {
    symbol: 'KLAY',
    name: 'Klaytn',
    exchange: 'CRYPTO',
    currentPrice: 0.178,
    previousClose: 0.173,
    change: 0.005,
    changePercent: 2.89,
    logoUrl: 'https://cryptologos.cc/logos/klaytn-klay-logo.png',
    sector: 'Cryptocurrency',
    description: 'https://www.klaytn.foundation/',
    assetType: 'crypto'
  },
  {
    symbol: 'ONE',
    name: 'Harmony',
    exchange: 'CRYPTO',
    currentPrice: 0.011,
    previousClose: 0.0105,
    change: 0.0005,
    changePercent: 4.76,
    logoUrl: 'https://cryptologos.cc/logos/harmony-one-logo.png',
    sector: 'Cryptocurrency',
    description: 'https://www.harmony.one/',
    assetType: 'crypto'
  },
  {
    symbol: 'HOT',
    name: 'Holo',
    exchange: 'CRYPTO',
    currentPrice: 0.0024,
    previousClose: 0.0023,
    change: 0.0001,
    changePercent: 4.35,
    logoUrl: 'https://cryptologos.cc/logos/holo-hot-logo.png',
    sector: 'Cryptocurrency',
    description: 'https://holochain.org/',
    assetType: 'crypto'
  },
  {
    symbol: 'CHZ',
    name: 'Chiliz',
    exchange: 'CRYPTO',
    currentPrice: 0.089,
    previousClose: 0.086,
    change: 0.003,
    changePercent: 3.49,
    logoUrl: 'https://cryptologos.cc/logos/chiliz-chz-logo.png',
    sector: 'Cryptocurrency',
    description: 'https://www.chiliz.com/',
    assetType: 'crypto'
  },
  {
    symbol: 'AMP',
    name: 'Amp',
    exchange: 'CRYPTO',
    currentPrice: 0.0034,
    previousClose: 0.0033,
    change: 0.0001,
    changePercent: 3.03,
    logoUrl: 'https://cryptologos.cc/logos/amp-amp-logo.png',
    sector: 'Cryptocurrency',
    description: 'https://amptoken.org/',
    assetType: 'crypto'
  },
  {
    symbol: 'ZRX',
    name: '0x',
    exchange: 'CRYPTO',
    currentPrice: 0.32,
    previousClose: 0.31,
    change: 0.01,
    changePercent: 3.23,
    logoUrl: 'https://cryptologos.cc/logos/0x-zrx-logo.png',
    sector: 'Cryptocurrency',
    description: 'https://0x.org/',
    assetType: 'crypto'
  },
  {
    symbol: 'BAT',
    name: 'Basic Attention Token',
    exchange: 'CRYPTO',
    currentPrice: 0.23,
    previousClose: 0.22,
    change: 0.01,
    changePercent: 4.55,
    logoUrl: 'https://cryptologos.cc/logos/basic-attention-token-bat-logo.png',
    sector: 'Cryptocurrency',
    description: 'https://basicattentiontoken.org/',
    assetType: 'crypto'
  },
  {
    symbol: 'IOTA',
    name: 'IOTA',
    exchange: 'CRYPTO',
    currentPrice: 0.167,
    previousClose: 0.162,
    change: 0.005,
    changePercent: 3.09,
    logoUrl: 'https://cryptologos.cc/logos/iota-miota-logo.png',
    sector: 'Cryptocurrency',
    description: 'https://www.iota.org/',
    assetType: 'crypto'
  },
  {
    symbol: 'NEO',
    name: 'NEO',
    exchange: 'CRYPTO',
    currentPrice: 11.23,
    previousClose: 10.92,
    change: 0.31,
    changePercent: 2.84,
    logoUrl: 'https://cryptologos.cc/logos/neo-neo-logo.png',
    sector: 'Cryptocurrency',
    description: 'https://neo.org/',
    assetType: 'crypto'
  },
  {
    symbol: 'ZIL',
    name: 'Zilliqa',
    exchange: 'CRYPTO',
    currentPrice: 0.0187,
    previousClose: 0.0181,
    change: 0.0006,
    changePercent: 3.31,
    logoUrl: 'https://cryptologos.cc/logos/zilliqa-zil-logo.png',
    sector: 'Cryptocurrency',
    description: 'https://www.zilliqa.com/',
    assetType: 'crypto'
  },
  {
    symbol: 'RUNE',
    name: 'THORChain',
    exchange: 'CRYPTO',
    currentPrice: 4.56,
    previousClose: 4.42,
    change: 0.14,
    changePercent: 3.17,
    logoUrl: 'https://cryptologos.cc/logos/thorchain-rune-logo.png',
    sector: 'Cryptocurrency',
    description: 'https://thorchain.org/',
    assetType: 'crypto'
  },
  {
    symbol: 'FLOW',
    name: 'Flow',
    exchange: 'CRYPTO',
    currentPrice: 0.67,
    previousClose: 0.65,
    change: 0.02,
    changePercent: 3.08,
    logoUrl: 'https://cryptologos.cc/logos/flow-flow-logo.png',
    sector: 'Cryptocurrency',
    description: 'https://flow.com/',
    assetType: 'crypto'
  },
  {
    symbol: 'QTUM',
    name: 'Qtum',
    exchange: 'CRYPTO',
    currentPrice: 2.87,
    previousClose: 2.78,
    change: 0.09,
    changePercent: 3.24,
    logoUrl: 'https://cryptologos.cc/logos/qtum-qtum-logo.png',
    sector: 'Cryptocurrency',
    description: 'https://qtum.org/',
    assetType: 'crypto'
  },
  {
    symbol: 'ONT',
    name: 'Ontology',
    exchange: 'CRYPTO',
    currentPrice: 0.23,
    previousClose: 0.22,
    change: 0.01,
    changePercent: 4.55,
    logoUrl: 'https://cryptologos.cc/logos/ontology-ont-logo.png',
    sector: 'Cryptocurrency',
    description: 'https://ont.io/',
    assetType: 'crypto'
  },
  {
    symbol: 'CKB',
    name: 'Nervos Network',
    exchange: 'CRYPTO',
    currentPrice: 0.0045,
    previousClose: 0.0043,
    change: 0.0002,
    changePercent: 4.65,
    logoUrl: 'https://cryptologos.cc/logos/nervos-network-ckb-logo.png',
    sector: 'Cryptocurrency',
    description: 'https://www.nervos.org/',
    assetType: 'crypto'
  },
  {
    symbol: 'THETA',
    name: 'Theta Network',
    exchange: 'CRYPTO',
    currentPrice: 0.98,
    previousClose: 0.95,
    change: 0.03,
    changePercent: 3.16,
    logoUrl: 'https://cryptologos.cc/logos/theta-network-theta-logo.png',
    sector: 'Cryptocurrency',
    description: 'https://www.thetatoken.org/',
    assetType: 'crypto'
  },
  {
    symbol: 'XTZ',
    name: 'Tezos',
    exchange: 'CRYPTO',
    currentPrice: 0.87,
    previousClose: 0.84,
    change: 0.03,
    changePercent: 3.57,
    logoUrl: 'https://cryptologos.cc/logos/tezos-xtz-logo.png',
    sector: 'Cryptocurrency',
    description: 'https://tezos.com/',
    assetType: 'crypto'
  },
  {
    symbol: 'ICX',
    name: 'ICON',
    exchange: 'CRYPTO',
    currentPrice: 0.23,
    previousClose: 0.22,
    change: 0.01,
    changePercent: 4.55,
    logoUrl: 'https://cryptologos.cc/logos/icon-icx-logo.png',
    sector: 'Cryptocurrency',
    description: 'https://iconrepublic.org/',
    assetType: 'crypto'
  },
  {
    symbol: 'OCEAN',
    name: 'Ocean Protocol',
    exchange: 'CRYPTO',
    currentPrice: 0.56,
    previousClose: 0.54,
    change: 0.02,
    changePercent: 3.70,
    logoUrl: 'https://cryptologos.cc/logos/ocean-protocol-ocean-logo.png',
    sector: 'Cryptocurrency',
    description: 'https://oceanprotocol.com/',
    assetType: 'crypto'
  },
  {
    symbol: 'WAVES',
    name: 'Waves',
    exchange: 'CRYPTO',
    currentPrice: 2.34,
    previousClose: 2.27,
    change: 0.07,
    changePercent: 3.08,
    logoUrl: 'https://cryptologos.cc/logos/waves-waves-logo.png',
    sector: 'Cryptocurrency',
    description: 'https://waves.tech/',
    assetType: 'crypto'
  },
  {
    symbol: 'BTG',
    name: 'Bitcoin Gold',
    exchange: 'CRYPTO',
    currentPrice: 32.45,
    previousClose: 31.23,
    change: 1.22,
    changePercent: 3.91,
    logoUrl: 'https://cryptologos.cc/logos/bitcoin-gold-btg-logo.png',
    sector: 'Cryptocurrency',
    description: 'https://bitcoingold.org/',
    assetType: 'crypto'
  },
  {
    symbol: 'SC',
    name: 'Siacoin',
    exchange: 'CRYPTO',
    currentPrice: 0.0039,
    previousClose: 0.0037,
    change: 0.0002,
    changePercent: 5.41,
    logoUrl: 'https://cryptologos.cc/logos/siacoin-sc-logo.png',
    sector: 'Cryptocurrency',
    description: 'https://sia.tech/',
    assetType: 'crypto'
  },
  {
    symbol: 'RVN',
    name: 'Ravencoin',
    exchange: 'CRYPTO',
    currentPrice: 0.0183,
    previousClose: 0.0178,
    change: 0.0005,
    changePercent: 2.81,
    logoUrl: 'https://cryptologos.cc/logos/ravencoin-rvn-logo.png',
    sector: 'Cryptocurrency',
    description: 'https://ravencoin.org/',
    assetType: 'crypto'
  },
  {
    symbol: 'DCR',
    name: 'Decred',
    exchange: 'CRYPTO',
    currentPrice: 15.67,
    previousClose: 15.23,
    change: 0.44,
    changePercent: 2.89,
    logoUrl: 'https://cryptologos.cc/logos/decred-dcr-logo.png',
    sector: 'Cryptocurrency',
    description: 'https://decred.org/',
    assetType: 'crypto'
  },
  {
    symbol: 'SNX',
    name: 'Synthetix',
    exchange: 'CRYPTO',
    currentPrice: 3.56,
    previousClose: 3.45,
    change: 0.11,
    changePercent: 3.19,
    logoUrl: 'https://cryptologos.cc/logos/synthetix-network-token-snx-logo.png',
    sector: 'Cryptocurrency',
    description: 'https://synthetix.io/',
    assetType: 'crypto'
  },
  {
    symbol: 'HBAR',
    name: 'Hedera',
    exchange: 'CRYPTO',
    currentPrice: 0.076,
    previousClose: 0.073,
    change: 0.003,
    changePercent: 4.11,
    logoUrl: 'https://cryptologos.cc/logos/hedera-hbar-logo.png',
    sector: 'Cryptocurrency',
    description: 'https://hedera.com/',
    assetType: 'crypto'
  },
  {
    symbol: 'BLUR',
    name: 'Blur',
    exchange: 'CRYPTO',
    currentPrice: 0.58,
    previousClose: 0.56,
    change: 0.02,
    changePercent: 3.57,
    logoUrl: 'https://cryptologos.cc/logos/blur-blur-logo.png',
    sector: 'Cryptocurrency',
    description: 'https://blur.io/',
    assetType: 'crypto'
  },
  {
    symbol: 'PYUSD',
    name: 'PayPal USD',
    exchange: 'CRYPTO',
    currentPrice: 1.0001,
    previousClose: 1.0000,
    change: 0.0001,
    changePercent: 0.01,
    logoUrl: 'https://cryptologos.cc/logos/paypal-usd-pyusd-logo.png',
    sector: 'Cryptocurrency',
    description: 'https://www.paypal.com/',
    assetType: 'crypto'
  },
  {
    symbol: 'BONK',
    name: 'Bonk',
    exchange: 'CRYPTO',
    currentPrice: 0.000019,
    previousClose: 0.000018,
    change: 0.000001,
    changePercent: 5.56,
    logoUrl: 'https://cryptologos.cc/logos/bonk-bonk-logo.png',
    sector: 'Cryptocurrency',
    description: 'https://bonkcoin.com/',
    assetType: 'crypto'
  },
  {
    symbol: 'WIF',
    name: 'Dogwifhat',
    exchange: 'CRYPTO',
    currentPrice: 2.12,
    previousClose: 2.05,
    change: 0.07,
    changePercent: 3.41,
    logoUrl: 'https://cryptologos.cc/logos/dogwifhat-wif-logo.png',
    sector: 'Cryptocurrency',
    description: 'https://dogwifcoin.org/',
    assetType: 'crypto'
  },
  {
    symbol: 'PEPE',
    name: 'Pepe',
    exchange: 'CRYPTO',
    currentPrice: 0.000009,
    previousClose: 0.0000086,
    change: 0.0000004,
    changePercent: 4.65,
    logoUrl: 'https://cryptologos.cc/logos/pepe-pepe-logo.png',
    sector: 'Cryptocurrency',
    description: 'https://www.pepe.vip/',
    assetType: 'crypto'
  },
  {
    symbol: 'FLOKI',
    name: 'Floki',
    exchange: 'CRYPTO',
    currentPrice: 0.0001423,
    previousClose: 0.0001376,
    change: 0.0000047,
    changePercent: 3.42,
    logoUrl: 'https://cryptologos.cc/logos/floki-inu-floki-logo.png',
    sector: 'Cryptocurrency',
    description: 'https://floki.com/',
    assetType: 'crypto'
  },
  {
    symbol: 'RNDR',
    name: 'Render',
    exchange: 'CRYPTO',
    currentPrice: 7.34,
    previousClose: 7.12,
    change: 0.22,
    changePercent: 3.09,
    logoUrl: 'https://cryptologos.cc/logos/render-token-rndr-logo.png',
    sector: 'Cryptocurrency',
    description: 'https://rendernetwork.com/',
    assetType: 'crypto'
  },
  {
    symbol: 'XDC',
    name: 'XDC Network',
    exchange: 'CRYPTO',
    currentPrice: 0.068,
    previousClose: 0.066,
    change: 0.002,
    changePercent: 3.03,
    logoUrl: 'https://cryptologos.cc/logos/xdc-network-xdc-logo.png',
    sector: 'Cryptocurrency',
    description: 'https://xinfin.org/',
    assetType: 'crypto'
  },
  {
    symbol: 'TIA',
    name: 'Celestia',
    exchange: 'CRYPTO',
    currentPrice: 16.78,
    previousClose: 16.21,
    change: 0.57,
    changePercent: 3.52,
    logoUrl: 'https://cryptologos.cc/logos/celestia-tia-logo.png',
    sector: 'Cryptocurrency',
    description: 'https://celestia.org/',
    assetType: 'crypto'
  },
  {
    symbol: 'JUP',
    name: 'Jupiter',
    exchange: 'CRYPTO',
    currentPrice: 0.67,
    previousClose: 0.64,
    change: 0.03,
    changePercent: 4.69,
    logoUrl: 'https://cryptologos.cc/logos/jupiter-jup-logo.png',
    sector: 'Cryptocurrency',
    description: 'https://jup.ag/',
    assetType: 'crypto'
  },
  {
    symbol: 'WEMIX',
    name: 'WEMIX',
    exchange: 'CRYPTO',
    currentPrice: 1.89,
    previousClose: 1.82,
    change: 0.07,
    changePercent: 3.85,
    logoUrl: 'https://cryptologos.cc/logos/wemix-wemix-logo.png',
    sector: 'Cryptocurrency',
    description: 'https://wemix.com/',
    assetType: 'crypto'
  },
  {
    symbol: 'BSV',
    name: 'Bitcoin SV',
    exchange: 'CRYPTO',
    currentPrice: 63.42,
    previousClose: 61.23,
    change: 2.19,
    changePercent: 3.58,
    logoUrl: 'https://cryptologos.cc/logos/bitcoin-sv-bsv-logo.png',
    sector: 'Cryptocurrency',
    description: 'https://bitcoinsv.com/',
    assetType: 'crypto'
  },
  {
    symbol: 'MINA',
    name: 'Mina Protocol',
    exchange: 'CRYPTO',
    currentPrice: 0.78,
    previousClose: 0.75,
    change: 0.03,
    changePercent: 4.00,
    logoUrl: 'https://cryptologos.cc/logos/mina-protocol-mina-logo.png',
    sector: 'Cryptocurrency',
    description: 'https://minaprotocol.com/',
    assetType: 'crypto'
  },
  {
    symbol: 'ETHW',
    name: 'EthereumPoW',
    exchange: 'CRYPTO',
    currentPrice: 2.12,
    previousClose: 2.05,
    change: 0.07,
    changePercent: 3.41,
    logoUrl: 'https://cryptologos.cc/logos/ethereum-pow-ethw-logo.png',
    sector: 'Cryptocurrency',
    description: 'https://ethereumpow.org/',
    assetType: 'crypto'
  },
  {
    symbol: 'WLD',
    name: 'Worldcoin',
    exchange: 'CRYPTO',
    currentPrice: 5.76,
    previousClose: 5.54,
    change: 0.22,
    changePercent: 3.97,
    logoUrl: 'https://cryptologos.cc/logos/worldcoin-wld-logo.png',
    sector: 'Cryptocurrency',
    description: 'https://worldcoin.org/',
    assetType: 'crypto'
  },
  {
    symbol: 'LUNC',
    name: 'Terra Classic',
    exchange: 'CRYPTO',
    currentPrice: 0.0000901,
    previousClose: 0.0000876,
    change: 0.0000025,
    changePercent: 2.85,
    logoUrl: 'https://cryptologos.cc/logos/terra-luna-lunc-logo.png',
    sector: 'Cryptocurrency',
    description: 'https://www.terra.money/',
    assetType: 'crypto'
  },
  {
    symbol: 'HOOK',
    name: 'Hooked Protocol',
    exchange: 'CRYPTO',
    currentPrice: 1.23,
    previousClose: 1.19,
    change: 0.04,
    changePercent: 3.36,
    logoUrl: 'https://cryptologos.cc/logos/hooked-protocol-hook-logo.png',
    sector: 'Cryptocurrency',
    description: 'https://hooked.io/',
    assetType: 'crypto'
  }
];